services:
  - type: web
    name: proyecto-mortalidad
    env: python
    plan: free
    region: oregon
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:server --workers=2 --threads=8 --timeout=120"
    autoDeploy: true
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
